server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: C:\Users\pphala\Desktop\Code\DropBookmarks\dropbookmark.keystore
      keyStorePassword: qwerty
      validateCerts: false

password: password

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3306/DropBookmarks